---
title: "Intro to Tidyverse"
author: "Charlie Carpenter"
output: html_document
---

https://rviews.rstudio.com/2017/06/08/what-is-the-tidyverse/#:~:text=The%20tidyverse%20is%20a%20coherent,being%20expanded%20by%20several%20contributors.

## Introduce Tidyverse
1. Philosophy behind it
  a. Hal Abelson: “Programs must be written for people to read and only incidentally for machines to execute”. 

2. Example of hard to read code and compare to easier to read tidyverse code

3. tidyverse is very big so we can't cover it all. 
  a. everyone is probably already familiar with `ggplot2`

## Introduce the Pipe
We will use it throughout

## Examples of base functions and tidyverse
1. subset vs. filter
3. merge vs. left_, right_, and full_join
2. tapply vs. group_by + summarize or mutate
4. Others?

## Syntax
Combine large data opperation into one single flow vs. a multistep opperation with nested () or multiple names

Phil Karlton - "There are only two hard things in Computer Science: cache invalidation and naming things."

## Advantages


## Disadvantages
1. Still a 'work in progress'
  a. melt/cast -> gather/spread -> pivot_longer/pivot_wider

2. "Rectangular" data structure isn't adopted by everyone. Bioconductor doesn't play very well with tidyverse for this reason. tidyverse doesn't really work with S4 objects



